apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-config
  namespace: capa-ci-tracker
  labels:
    app.kubernetes.io/part-of: capa-ci-tracker
    app.kubernetes.io/component: api
data:
  PGRST_DB_SCHEMA: "public"
  PGRST_DB_ANON_ROLE: "postgrest_anon"
  PGRST_DB_MAX_ROWS: "1000"
  PGRST_OPENAPI_SERVER_PROXY_URI: "https://capa-ci-tracker.apps.CLUSTER_DOMAIN/api"
