apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capa-ci-tracker

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - configmap.yaml
  - secret-env.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
