apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capa-ci-tracker-data
  namespace: capa-ci-tracker
  labels:
    app.kubernetes.io/name: capa-ci-tracker
    app.kubernetes.io/part-of: capa-ci-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
