apiVersion: v1
kind: Secret
metadata:
  name: capa-ci-tracker-env
  namespace: capa-ci-tracker
  labels:
    app.kubernetes.io/name: capa-ci-tracker
    app.kubernetes.io/part-of: capa-ci-tracker
type: Opaque
stringData:
  JENKINS_BASE_URL: REPLACE_ME
  JENKINS_USER: REPLACE_ME
  JENKINS_API_TOKEN: REPLACE_ME
  GITHUB_TOKEN: REPLACE_ME
  SLACK_WEBHOOK_URL: REPLACE_ME
  JENKINS_SKIP_TLS: "false"
