apiVersion: v1
kind: ServiceAccount
metadata:
  name: capa-ci-tracker
  namespace: capa-ci-tracker
  labels:
    app.kubernetes.io/name: capa-ci-tracker
    app.kubernetes.io/part-of: capa-ci-tracker
