apiVersion: v1
kind: Service
metadata:
  name: capa-ci-tracker
  namespace: capa-ci-tracker
  labels:
    app.kubernetes.io/name: capa-ci-tracker
    app.kubernetes.io/part-of: capa-ci-tracker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: capa-ci-tracker
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
